version: '3'
# 실행명령어
services:
  novelcia-mysql:
    image: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: novelcia
      MYSQL_ROOT_PASSWORD: root
  redis-local:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  redis-insight:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    restart: always
    volumes:
      - ./redis-insight-data:/data
  novelcia-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: novelcia