spring:
  datasource:
    url: "jdbc:h2:mem:novelcia;"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql.init.mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis: # redis auto-config ?? (RedisProperties ? ???? ??)
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
      uri: mongodb://root:root@localhost:27017/search?authSource=admin
      authentication-database: admin
---
spring: # local profile
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/novelcia?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      defer-datasource-initialization: false
  sql.init.mode: never
  h2.console.enabled: false
