spring: # test profile
  application:
    name: novelcia-api-server
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888}
    name: novelcia-api-server
  profiles:
    include:
      - session
      - database
      - logging
      - docs
      - server
      - task
      - batch