apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      environment: local
  template:
    metadata:
      labels:
        app: mysql
        environment: local
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  # MySQL 이미지 사용
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "novelcia"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 필요에 따라 크기를 조정

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
    environment: local
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306