apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      environment: local
  template:
    metadata:
      labels:
        app: redis
        environment: local
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
    environment: local
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
