apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot
    environment: local
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
      environment: local
  template:
    metadata:
      labels:
        app: spring-boot
        environment: local
    spec:
      containers:
        - name: spring-boot
          image: your-spring-boot-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis-service"  # Kubernetes service name for Redis
            - name: REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/novelcia"
          readinessProbe:
            httpGet:
              path: "/api/test/health"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: "/api/test/health"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
    environment: local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
